# Generated by Django 5.0.3 on 2024-03-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('genre', models.TextField()),
                ('book_url', models.URLField()),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('tags', models.TextField()),
                ('description', models.TextField()),
                ('rating', models.CharField(max_length=4)),
                ('ratings_nb', models.CharField(max_length=10)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
