# Generated by Django 5.0.3 on 2024-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='library_book_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='similar_books',
            field=models.CharField(default='', max_length=255),
        ),
    ]
